# Site settings
title: "PCT's Blog"
description: >-
  I am an Infosec enthusiast. I like doing Hack The Box and TryHackMe challenges.
  I enjoy learning new things in my spare time.

twitter_username: 7rootsec
github_username: 7rootsec

minimal_mistakes_skin: yellow
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 100
paginate_path: /page:num/
timezone: Africa/Casablanca

include:
  - _pages

# Plugins (GitHub Pages allowed)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# Author
author:
  name   : "PCT"
  avatar : "/assets/images/b5cf24f912d5d0c6e4e775649a342384.jpg"
  bio    : "Infosec Enthusiast"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/7rootsec"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/7rootsec"

# Defaults
defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
      show_date: true

  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
